name: Deploy to CloudFlare
on: [push]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Deploy to CloudFlare
      uses: cloudflare/wrangler-action@1.3.0
      with:
        apiKey: ${{ secrets.CLOUDFLARE_API_KEY }}
        email: ${{ secrets.CLOUDFLARE_EMAIL }}
        environment: 'production'